server:
  port: 8081

jwt.secret: wozaijiayuancccsadkjsahteipwirpa;fksa,fasmgiajsvnasfskalfjaslfdfasfcvdffscvdafdgdsagcveregdfgav

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: x208820
    type: com.zaxxer.hikari.HikariDataSource